const PREP_DATA = {
  verbs: [

{pattern:"depend on",word:"depend",prep:"on",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"bağlı olmak",example:"Success depends on effort.",trap:["depend from"],patternNote:"depend on + noun/gerund"},
{pattern:"result in",word:"result",prep:"in",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"ile sonuçlanmak",example:"The reform resulted in economic growth.",trap:["result to"],patternNote:"result in + noun"},
{pattern:"result from",word:"result",prep:"from",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"-den kaynaklanmak",example:"The crisis resulted from mismanagement.",trap:[],patternNote:"result from + cause"},
{pattern:"lead to",word:"lead",prep:"to",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"-e yol açmak",example:"Lack of sleep leads to errors.",trap:[],patternNote:"lead to + noun"},
{pattern:"contribute to",word:"contribute",prep:"to",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"katkıda bulunmak",example:"Pollution contributes to climate change.",trap:[],patternNote:"contribute to + noun/gerund"},
{pattern:"suffer from",word:"suffer",prep:"from",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"çekmek",example:"Many patients suffer from anxiety.",trap:[],patternNote:"suffer from + illness/problem"},
{pattern:"cope with",word:"cope",prep:"with",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"başa çıkmak",example:"Students cope with pressure.",trap:[],patternNote:"cope with + noun"},
{pattern:"deal with",word:"deal",prep:"with",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"ilgilenmek",example:"The article deals with inflation.",trap:[],patternNote:"deal with + topic"},
{pattern:"focus on",word:"focus",prep:"on",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"odaklanmak",example:"The study focuses on language.",trap:[],patternNote:"focus on + noun"},
{pattern:"concentrate on",word:"concentrate",prep:"on",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"yoğunlaşmak",example:"She concentrated on her task.",trap:[],patternNote:"concentrate on + noun"},
{pattern:"belong to",word:"belong",prep:"to",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"ait olmak",example:"This book belongs to me.",trap:[],patternNote:"belong to + person"},
{pattern:"refer to",word:"refer",prep:"to",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"atıfta bulunmak",example:"The author refers to past research.",trap:[],patternNote:"refer to + noun"},
{pattern:"apply to",word:"apply",prep:"to",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"geçerli olmak",example:"The rule applies to everyone.",trap:[],patternNote:"apply to + noun"},
{pattern:"approve of",word:"approve",prep:"of",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"onaylamak",example:"They approve of the decision.",trap:["approve"],patternNote:"approve of + noun/gerund"},
{pattern:"object to",word:"object",prep:"to",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"itiraz etmek",example:"Residents object to the plan.",trap:[],patternNote:"object to + noun/gerund"},
{pattern:"account for",word:"account",prep:"for",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"açıklamak / oluşturmak",example:"Exports account for 30% of income.",trap:[],patternNote:"account for + percentage"},
{pattern:"consist of",word:"consist",prep:"of",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"-den oluşmak",example:"The team consists of experts.",trap:["consist from"],patternNote:"consist of + parts"},
{pattern:"rely on",word:"rely",prep:"on",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"güvenmek",example:"We rely on data.",trap:[],patternNote:"rely on + noun"},
{pattern:"insist on",word:"insist",prep:"on",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"ısrar etmek",example:"She insisted on paying.",trap:[],patternNote:"insist on + gerund"},
{pattern:"arise from",word:"arise",prep:"from",type:"Verb + Prep",risk:"very-high",academic:true,turkish:"-den doğmak",example:"Problems arise from conflict.",trap:[],patternNote:"arise from + cause"},

/* ================= HIGH ================= */

{pattern:"engage in",word:"engage",prep:"in",type:"Verb + Prep",risk:"high",academic:true,turkish:"katılmak",example:"Students engage in discussion.",trap:[],patternNote:"engage in + activity"},
{pattern:"participate in",word:"participate",prep:"in",type:"Verb + Prep",risk:"high",academic:true,turkish:"katılmak",example:"He participated in the event.",trap:[],patternNote:"participate in + noun"},
{pattern:"invest in",word:"invest",prep:"in",type:"Verb + Prep",risk:"high",academic:true,turkish:"yatırım yapmak",example:"They invested in technology.",trap:[],patternNote:"invest in + noun"},
{pattern:"comply with",word:"comply",prep:"with",type:"Verb + Prep",risk:"high",academic:true,turkish:"uymak",example:"Firms must comply with regulations.",trap:[],patternNote:"comply with + rule"},
{pattern:"attribute to",word:"attribute",prep:"to",type:"Verb + Prep",risk:"high",academic:true,turkish:"-e atfetmek",example:"She attributed success to luck.",trap:[],patternNote:"attribute to + cause"},
{pattern:"benefit from",word:"benefit",prep:"from",type:"Verb + Prep",risk:"high",academic:true,turkish:"yararlanmak",example:"Students benefit from feedback.",trap:[],patternNote:"benefit from + noun"},
{pattern:"emerge from",word:"emerge",prep:"from",type:"Verb + Prep",risk:"high",academic:true,turkish:"ortaya çıkmak",example:"A solution emerged from talks.",trap:[],patternNote:"emerge from + process"},
{pattern:"stem from",word:"stem",prep:"from",type:"Verb + Prep",risk:"high",academic:true,turkish:"kaynaklanmak",example:"The issue stems from policy.",trap:[],patternNote:"stem from + cause"},
{pattern:"specialize in",word:"specialize",prep:"in",type:"Verb + Prep",risk:"high",academic:true,turkish:"uzmanlaşmak",example:"She specializes in linguistics.",trap:[],patternNote:"specialize in + field"},
{pattern:"react to",word:"react",prep:"to",type:"Verb + Prep",risk:"high",academic:true,turkish:"tepki vermek",example:"Markets reacted to news.",trap:[],patternNote:"react to + event"},
{pattern:"adapt to",word:"adapt",prep:"to",type:"Verb + Prep",risk:"high",academic:true,turkish:"uyum sağlamak",example:"Animals adapt to new environments.",trap:[],patternNote:"adapt to + noun"},
{pattern:"adjust to",word:"adjust",prep:"to",type:"Verb + Prep",risk:"high",academic:true,turkish:"alışmak / uyum sağlamak",example:"He adjusted to city life.",trap:[],patternNote:"adjust to + noun"},
{pattern:"appeal to",word:"appeal",prep:"to",type:"Verb + Prep",risk:"high",academic:true,turkish:"hitap etmek",example:"The idea appeals to young voters.",trap:[],patternNote:"appeal to + person/group"},
{pattern:"believe in",word:"believe",prep:"in",type:"Verb + Prep",risk:"high",academic:false,turkish:"inanmak",example:"She believes in equality.",trap:[],patternNote:"believe in + noun"},
{pattern:"care about",word:"care",prep:"about",type:"Verb + Prep",risk:"high",academic:false,turkish:"önemsemek",example:"They care about the issue.",trap:[],patternNote:"care about + noun"},
{pattern:"care for",word:"care",prep:"for",type:"Verb + Prep",risk:"high",academic:false,turkish:"bakmak / sevmek",example:"She cares for elderly people.",trap:[],patternNote:"care for + person"},
{pattern:"comment on",word:"comment",prep:"on",type:"Verb + Prep",risk:"high",academic:true,turkish:"yorum yapmak",example:"He commented on the proposal.",trap:[],patternNote:"comment on + noun"},
{pattern:"compete with",word:"compete",prep:"with",type:"Verb + Prep",risk:"high",academic:true,turkish:"rekabet etmek",example:"Local firms compete with global brands.",trap:[],patternNote:"compete with + competitor"},
{pattern:"complain about",word:"complain",prep:"about",type:"Verb + Prep",risk:"high",academic:false,turkish:"şikayet etmek",example:"Customers complained about delays.",trap:[],patternNote:"complain about + problem"},
{pattern:"consent to",word:"consent",prep:"to",type:"Verb + Prep",risk:"high",academic:true,turkish:"rıza göstermek",example:"He consented to the agreement.",trap:[],patternNote:"consent to + noun/gerund"},
{pattern:"consent with",word:"consent",prep:"with",type:"Verb + Prep",risk:"high",academic:false,turkish:"aynı fikirde olmak",example:"I consent with your opinion.",trap:[],patternNote:"rare usage"},
{pattern:"contrast with",word:"contrast",prep:"with",type:"Verb + Prep",risk:"high",academic:true,turkish:"zıtlık göstermek",example:"This contrasts with earlier findings.",trap:[],patternNote:"contrast with + noun"},
{pattern:"dedicate to",word:"dedicate",prep:"to",type:"Verb + Prep",risk:"high",academic:true,turkish:"adamak",example:"She dedicated her life to science.",trap:[],patternNote:"dedicate to + noun/gerund"},
{pattern:"derive from",word:"derive",prep:"from",type:"Verb + Prep",risk:"high",academic:true,turkish:"-den türemek",example:"The word derives from Latin.",trap:[],patternNote:"derive from + origin"},
{pattern:"differ from",word:"differ",prep:"from",type:"Verb + Prep",risk:"high",academic:true,turkish:"farklı olmak",example:"This differs from the original plan.",trap:["different than"],patternNote:"differ from + noun"},
{pattern:"engage with",word:"engage",prep:"with",type:"Verb + Prep",risk:"high",academic:true,turkish:"etkileşimde bulunmak",example:"Students engage with material.",trap:[],patternNote:"engage with + noun"},
{pattern:"insure against",word:"insure",prep:"against",type:"Verb + Prep",risk:"high",academic:false,turkish:"sigorta yapmak",example:"They insured against fire.",trap:[],patternNote:"insure against + risk"},
{pattern:"insure for",word:"insure",prep:"for",type:"Verb + Prep",risk:"high",academic:false,turkish:"... için sigorta yapmak",example:"The house was insured for $200,000.",trap:[],patternNote:"insure for + amount"},
{pattern:"interfere with",word:"interfere",prep:"with",type:"Verb + Prep",risk:"high",academic:true,turkish:"müdahale etmek",example:"Noise interferes with concentration.",trap:[],patternNote:"interfere with + noun"},
{pattern:"look after",word:"look",prep:"after",type:"Verb + Prep",risk:"high",academic:false,turkish:"ilgilenmek / bakmak",example:"She looks after her sister.",trap:[],patternNote:"look after + person"},

/* ================= MEDIUM ================= */

{pattern:"aim at",word:"aim",prep:"at",type:"Verb + Prep",risk:"medium",academic:true,turkish:"amaçlamak",example:"The policy aims at reform.",trap:[],patternNote:"aim at + noun"},
{pattern:"apologize for",word:"apologize",prep:"for",type:"Verb + Prep",risk:"medium",academic:false,turkish:"özür dilemek",example:"He apologized for being late.",trap:[],patternNote:"apologize for + gerund"},
{pattern:"arrive at",word:"arrive",prep:"at",type:"Verb + Prep",risk:"medium",academic:false,turkish:"varmak (küçük yer)",example:"They arrived at the station.",trap:[],patternNote:"arrive at + small place"},
{pattern:"arrive in",word:"arrive",prep:"in",type:"Verb + Prep",risk:"medium",academic:false,turkish:"varmak (şehir/ülke)",example:"She arrived in Paris.",trap:[],patternNote:"arrive in + city/country"},
{pattern:"ask for",word:"ask",prep:"for",type:"Verb + Prep",risk:"medium",academic:false,turkish:"istemek",example:"He asked for help.",trap:[],patternNote:"ask for + noun"},
{pattern:"believe in",word:"believe",prep:"in",type:"Verb + Prep",risk:"medium",academic:false,turkish:"inanmak",example:"They believe in justice.",trap:[],patternNote:"believe in + noun"},
{pattern:"borrow from",word:"borrow",prep:"from",type:"Verb + Prep",risk:"medium",academic:false,turkish:"ödünç almak",example:"She borrowed money from her friend.",trap:[],patternNote:"borrow from + person"},
{pattern:"call for",word:"call",prep:"for",type:"Verb + Prep",risk:"medium",academic:true,turkish:"gerektirmek",example:"The situation calls for action.",trap:[],patternNote:"call for + noun"},
{pattern:"care for",word:"care",prep:"for",type:"Verb + Prep",risk:"medium",academic:false,turkish:"bakmak",example:"She cares for children.",trap:[],patternNote:"care for + person"},
{pattern:"compare with",word:"compare",prep:"with",type:"Verb + Prep",risk:"medium",academic:true,turkish:"karşılaştırmak",example:"Compare this with the previous model.",trap:[],patternNote:"compare with + noun"},
{pattern:"compare to",word:"compare",prep:"to",type:"Verb + Prep",risk:"medium",academic:true,turkish:"benzetmek",example:"He compared her to a star.",trap:[],patternNote:"compare to + noun"},
{pattern:"dream of",word:"dream",prep:"of",type:"Verb + Prep",risk:"medium",academic:false,turkish:"hayal etmek",example:"She dreams of success.",trap:[],patternNote:"dream of + noun"},
{pattern:"escape from",word:"escape",prep:"from",type:"Verb + Prep",risk:"medium",academic:false,turkish:"kaçmak",example:"He escaped from prison.",trap:[],patternNote:"escape from + place"},
{pattern:"fight against",word:"fight",prep:"against",type:"Verb + Prep",risk:"medium",academic:false,turkish:"karşı savaşmak",example:"They fought against injustice.",trap:[],patternNote:"fight against + noun"},
{pattern:"hope for",word:"hope",prep:"for",type:"Verb + Prep",risk:"medium",academic:false,turkish:"umut etmek",example:"We hope for better days.",trap:[],patternNote:"hope for + noun"},
{pattern:"listen to",word:"listen",prep:"to",type:"Verb + Prep",risk:"medium",academic:false,turkish:"dinlemek",example:"Listen to the teacher.",trap:[],patternNote:"listen to + noun"},
{pattern:"look for",word:"look",prep:"for",type:"Verb + Prep",risk:"medium",academic:false,turkish:"aramak",example:"She looked for her keys.",trap:[],patternNote:"look for + noun"},
{pattern:"pay for",word:"pay",prep:"for",type:"Verb + Prep",risk:"medium",academic:false,turkish:"ödemek",example:"He paid for the meal.",trap:[],patternNote:"pay for + noun"},
{pattern:"prepare for",word:"prepare",prep:"for",type:"Verb + Prep",risk:"medium",academic:true,turkish:"hazırlanmak",example:"Students prepare for exams.",trap:[],patternNote:"prepare for + noun"},
{pattern:"search for",word:"search",prep:"for",type:"Verb + Prep",risk:"medium",academic:false,turkish:"aramak",example:"Police searched for evidence.",trap:[],patternNote:"search for + noun"}


],
  adjectives: [
    /* ================= VERY HIGH ================= */

{pattern:"afraid of",word:"afraid",prep:"of",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"korkmak",example:"She is afraid of spiders.",trap:[],patternNote:"afraid of + noun/gerund"},
{pattern:"aware of",word:"aware",prep:"of",type:"Adjective + Prep",risk:"very-high",academic:true,turkish:"farkında olmak",example:"She is aware of the risks.",trap:[],patternNote:"aware of + noun"},
{pattern:"capable of",word:"capable",prep:"of",type:"Adjective + Prep",risk:"very-high",academic:true,turkish:"yapabilir durumda",example:"He is capable of solving the problem.",trap:[],patternNote:"capable of + gerund"},
{pattern:"different from",word:"different",prep:"from",type:"Adjective + Prep",risk:"very-high",academic:true,turkish:"farklı",example:"This is different from that.",trap:["different than"],patternNote:"different from + noun"},
{pattern:"famous for",word:"famous",prep:"for",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"ile ünlü",example:"Italy is famous for its food.",trap:[],patternNote:"famous for + noun"},
{pattern:"good at",word:"good",prep:"at",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"iyi olmak",example:"She is good at math.",trap:[],patternNote:"good at + gerund/noun"},
{pattern:"interested in",word:"interested",prep:"in",type:"Adjective + Prep",risk:"very-high",academic:true,turkish:"ilgilenmek",example:"He is interested in science.",trap:[],patternNote:"interested in + noun/gerund"},
{pattern:"keen on",word:"keen",prep:"on",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"hevesli",example:"She is keen on music.",trap:[],patternNote:"keen on + noun/gerund"},
{pattern:"responsible for",word:"responsible",prep:"for",type:"Adjective + Prep",risk:"very-high",academic:true,turkish:"sorumlu",example:"She is responsible for the project.",trap:[],patternNote:"responsible for + noun"},
{pattern:"similar to",word:"similar",prep:"to",type:"Adjective + Prep",risk:"very-high",academic:true,turkish:"benzer",example:"This is similar to the original.",trap:[],patternNote:"similar to + noun"},
{pattern:"suitable for",word:"suitable",prep:"for",type:"Adjective + Prep",risk:"very-high",academic:true,turkish:"uygun",example:"This book is suitable for children.",trap:[],patternNote:"suitable for + noun"},
{pattern:"sure of",word:"sure",prep:"of",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"emin",example:"She is sure of her answer.",trap:[],patternNote:"sure of + noun"},
{pattern:"worried about",word:"worried",prep:"about",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"endişeli",example:"He is worried about the exam.",trap:[],patternNote:"worried about + noun"},
{pattern:"pleased with",word:"pleased",prep:"with",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"memnun",example:"She is pleased with the result.",trap:[],patternNote:"pleased with + noun"},
{pattern:"proud of",word:"proud",prep:"of",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"gururlu",example:"He is proud of his son.",trap:[],patternNote:"proud of + noun"},
{pattern:"accustomed to",word:"accustomed",prep:"to",type:"Adjective + Prep",risk:"very-high",academic:true,turkish:"alışkın",example:"She is accustomed to working hard.",trap:[],patternNote:"accustomed to + gerund"},
{pattern:"addicted to",word:"addicted",prep:"to",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"bağımlı",example:"He is addicted to coffee.",trap:[],patternNote:"addicted to + noun/gerund"},
{pattern:"married to",word:"married",prep:"to",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"evli",example:"She is married to a doctor.",trap:["married with"],patternNote:"married to + person"},
{pattern:"crowded with",word:"crowded",prep:"with",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"ile dolu",example:"The street was crowded with tourists.",trap:[],patternNote:"crowded with + noun"},
{pattern:"filled with",word:"filled",prep:"with",type:"Adjective + Prep",risk:"very-high",academic:false,turkish:"ile dolu",example:"The room was filled with smoke.",trap:[],patternNote:"filled with + noun"},

/* ================= HIGH ================= */

{pattern:"angry with",word:"angry",prep:"with",type:"Adjective + Prep",risk:"high",academic:false,turkish:"kızgın (kişiye)",example:"She is angry with him.",trap:[],patternNote:"angry with + person"},
{pattern:"angry about",word:"angry",prep:"about",type:"Adjective + Prep",risk:"high",academic:false,turkish:"kızgın (duruma)",example:"She is angry about the delay.",trap:[],patternNote:"angry about + situation"},
{pattern:"concerned about",word:"concerned",prep:"about",type:"Adjective + Prep",risk:"high",academic:true,turkish:"endişeli",example:"They are concerned about pollution.",trap:[],patternNote:"concerned about + noun"},
{pattern:"concerned with",word:"concerned",prep:"with",type:"Adjective + Prep",risk:"high",academic:true,turkish:"ilgili",example:"The study is concerned with language.",trap:[],patternNote:"concerned with + topic"},
{pattern:"content with",word:"content",prep:"with",type:"Adjective + Prep",risk:"high",academic:false,turkish:"memnun",example:"She is content with her job.",trap:[],patternNote:"content with + noun"},
{pattern:"critical of",word:"critical",prep:"of",type:"Adjective + Prep",risk:"high",academic:true,turkish:"eleştirel",example:"He is critical of the policy.",trap:[],patternNote:"critical of + noun"},
{pattern:"dependent on",word:"dependent",prep:"on",type:"Adjective + Prep",risk:"high",academic:true,turkish:"bağımlı",example:"Children are dependent on parents.",trap:[],patternNote:"dependent on + noun"},
{pattern:"eager to",word:"eager",prep:"to",type:"Adjective + Prep",risk:"high",academic:false,turkish:"istekli",example:"She is eager to learn.",trap:[],patternNote:"eager to + verb"},
{pattern:"familiar with",word:"familiar",prep:"with",type:"Adjective + Prep",risk:"high",academic:true,turkish:"aşina",example:"She is familiar with the topic.",trap:[],patternNote:"familiar with + noun"},
{pattern:"fond of",word:"fond",prep:"of",type:"Adjective + Prep",risk:"high",academic:false,turkish:"düşkün",example:"He is fond of music.",trap:[],patternNote:"fond of + noun"},
{pattern:"grateful to",word:"grateful",prep:"to",type:"Adjective + Prep",risk:"high",academic:false,turkish:"minnettar (kişiye)",example:"She is grateful to her teacher.",trap:[],patternNote:"grateful to + person"},
{pattern:"grateful for",word:"grateful",prep:"for",type:"Adjective + Prep",risk:"high",academic:false,turkish:"minnettar (şeye)",example:"She is grateful for your help.",trap:[],patternNote:"grateful for + noun"},
{pattern:"hostile to",word:"hostile",prep:"to",type:"Adjective + Prep",risk:"high",academic:true,turkish:"düşmanca",example:"They are hostile to change.",trap:[],patternNote:"hostile to + noun"},
{pattern:"immune to",word:"immune",prep:"to",type:"Adjective + Prep",risk:"high",academic:true,turkish:"bağışık",example:"She is immune to criticism.",trap:[],patternNote:"immune to + noun"},
{pattern:"inferior to",word:"inferior",prep:"to",type:"Adjective + Prep",risk:"high",academic:true,turkish:"daha aşağı",example:"This product is inferior to that.",trap:[],patternNote:"inferior to + noun"},
{pattern:"opposed to",word:"opposed",prep:"to",type:"Adjective + Prep",risk:"high",academic:true,turkish:"karşı",example:"They are opposed to the plan.",trap:[],patternNote:"opposed to + noun/gerund"},
{pattern:"prepared for",word:"prepared",prep:"for",type:"Adjective + Prep",risk:"high",academic:true,turkish:"hazır",example:"She is prepared for the exam.",trap:[],patternNote:"prepared for + noun"},
{pattern:"relevant to",word:"relevant",prep:"to",type:"Adjective + Prep",risk:"high",academic:true,turkish:"ilgili",example:"This is relevant to our topic.",trap:[],patternNote:"relevant to + noun"},
{pattern:"sensitive to",word:"sensitive",prep:"to",type:"Adjective + Prep",risk:"high",academic:true,turkish:"duyarlı",example:"She is sensitive to criticism.",trap:[],patternNote:"sensitive to + noun"},
{pattern:"superior to",word:"superior",prep:"to",type:"Adjective + Prep",risk:"high",academic:true,turkish:"üstün",example:"This is superior to the old model.",trap:[],patternNote:"superior to + noun"},

/* ================= MEDIUM (30 MORE) ================= */

{pattern:"afraid for",word:"afraid",prep:"for",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"... için endişeli",example:"She is afraid for her child.",trap:[],patternNote:"afraid for + person"},
{pattern:"anxious about",word:"anxious",prep:"about",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"kaygılı",example:"She is anxious about the result.",trap:[],patternNote:"anxious about + noun"},
{pattern:"anxious to",word:"anxious",prep:"to",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"istekli",example:"She is anxious to succeed.",trap:[],patternNote:"anxious to + verb"},
{pattern:"ashamed of",word:"ashamed",prep:"of",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"utanmış",example:"He is ashamed of his behavior.",trap:[],patternNote:"ashamed of + noun"},
{pattern:"aware that",word:"aware",prep:"that",type:"Adjective + Prep",risk:"medium",academic:true,turkish:"farkında (clause)",example:"She is aware that she is late.",trap:[],patternNote:"aware that + clause"},
{pattern:"busy with",word:"busy",prep:"with",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"meşgul",example:"She is busy with work.",trap:[],patternNote:"busy with + noun"},
{pattern:"certain of",word:"certain",prep:"of",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"emin",example:"She is certain of her success.",trap:[],patternNote:"certain of + noun"},
{pattern:"certain about",word:"certain",prep:"about",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"emin",example:"She is certain about the answer.",trap:[],patternNote:"certain about + noun"},
{pattern:"clever at",word:"clever",prep:"at",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"zeki",example:"He is clever at solving puzzles.",trap:[],patternNote:"clever at + gerund"},
{pattern:"different than",word:"different",prep:"than",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"(ABD kullanımı)",example:"This is different than I expected.",trap:[],patternNote:"US usage"},
{pattern:"equal to",word:"equal",prep:"to",type:"Adjective + Prep",risk:"medium",academic:true,turkish:"eşit",example:"Two plus two is equal to four.",trap:[],patternNote:"equal to + noun"},
{pattern:"excited about",word:"excited",prep:"about",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"heyecanlı",example:"She is excited about the trip.",trap:[],patternNote:"excited about + noun"},
{pattern:"full of",word:"full",prep:"of",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"ile dolu",example:"The room is full of people.",trap:[],patternNote:"full of + noun"},
{pattern:"happy about",word:"happy",prep:"about",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"mutlu",example:"She is happy about the news.",trap:[],patternNote:"happy about + noun"},
{pattern:"happy with",word:"happy",prep:"with",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"memnun",example:"She is happy with her score.",trap:[],patternNote:"happy with + noun"},
{pattern:"honest with",word:"honest",prep:"with",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"dürüst (kişiye)",example:"Be honest with me.",trap:[],patternNote:"honest with + person"},
{pattern:"honest about",word:"honest",prep:"about",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"dürüst (konuda)",example:"Be honest about your feelings.",trap:[],patternNote:"honest about + noun"},
{pattern:"kind to",word:"kind",prep:"to",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"nazik",example:"She is kind to children.",trap:[],patternNote:"kind to + person"},
{pattern:"late for",word:"late",prep:"for",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"geç kalmış",example:"She is late for class.",trap:[],patternNote:"late for + noun"},
{pattern:"loyal to",word:"loyal",prep:"to",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"sadık",example:"He is loyal to his friends.",trap:[],patternNote:"loyal to + noun"},
{pattern:"open to",word:"open",prep:"to",type:"Adjective + Prep",risk:"medium",academic:true,turkish:"açık",example:"She is open to suggestions.",trap:[],patternNote:"open to + noun"},
{pattern:"ready for",word:"ready",prep:"for",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"hazır",example:"She is ready for the exam.",trap:[],patternNote:"ready for + noun"},
{pattern:"rich in",word:"rich",prep:"in",type:"Adjective + Prep",risk:"medium",academic:true,turkish:"zengin",example:"This soil is rich in minerals.",trap:[],patternNote:"rich in + noun"},
{pattern:"safe from",word:"safe",prep:"from",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"güvende",example:"They are safe from danger.",trap:[],patternNote:"safe from + noun"},
{pattern:"short of",word:"short",prep:"of",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"eksik",example:"We are short of time.",trap:[],patternNote:"short of + noun"},
{pattern:"tired of",word:"tired",prep:"of",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"bıkmış",example:"She is tired of waiting.",trap:[],patternNote:"tired of + gerund"},
{pattern:"used to",word:"used",prep:"to",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"alışkın",example:"She is used to working late.",trap:[],patternNote:"used to + gerund"},
{pattern:"weak in",word:"weak",prep:"in",type:"Adjective + Prep",risk:"medium",academic:true,turkish:"zayıf",example:"He is weak in math.",trap:[],patternNote:"weak in + subject"},
{pattern:"worried about",word:"worried",prep:"about",type:"Adjective + Prep",risk:"medium",academic:false,turkish:"endişeli",example:"She is worried about her exam.",trap:[],patternNote:"worried about + noun"}

  ],

  nouns: [


/* ================= VERY HIGH ================= */

{pattern:"access to",word:"access",prep:"to",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"erişim",example:"Students need access to information.",trap:[],patternNote:"access to + noun"},
{pattern:"advantage of",word:"advantage",prep:"of",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"avantaj",example:"They took advantage of the opportunity.",trap:[],patternNote:"advantage of + noun"},
{pattern:"attitude toward",word:"attitude",prep:"toward",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"tutum",example:"Her attitude toward work is positive.",trap:["attitude against"],patternNote:"attitude toward + noun"},
{pattern:"attitude to",word:"attitude",prep:"to",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"tutum (BrE)",example:"His attitude to education is strict.",trap:[],patternNote:"attitude to + noun"},
{pattern:"belief in",word:"belief",prep:"in",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"inanç",example:"Belief in democracy is strong.",trap:[],patternNote:"belief in + noun"},
{pattern:"cause of",word:"cause",prep:"of",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"sebep",example:"The cause of the problem is unknown.",trap:[],patternNote:"cause of + noun"},
{pattern:"conclusion about",word:"conclusion",prep:"about",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"hakkında sonuç",example:"They reached a conclusion about the issue.",trap:[],patternNote:"conclusion about + noun"},
{pattern:"conclusion on",word:"conclusion",prep:"on",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"üzerine sonuç",example:"The study offers conclusions on climate change.",trap:[],patternNote:"conclusion on + topic"},
{pattern:"connection between",word:"connection",prep:"between",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"arasındaki bağlantı",example:"There is a connection between diet and health.",trap:[],patternNote:"connection between A and B"},
{pattern:"contribution to",word:"contribution",prep:"to",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"katkı",example:"Her contribution to science is significant.",trap:[],patternNote:"contribution to + noun"},
{pattern:"demand for",word:"demand",prep:"for",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"talep",example:"There is high demand for energy.",trap:[],patternNote:"demand for + noun"},
{pattern:"difference between",word:"difference",prep:"between",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"arasındaki fark",example:"The difference between the two models is clear.",trap:[],patternNote:"difference between A and B"},
{pattern:"effect on",word:"effect",prep:"on",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"üzerindeki etki",example:"The effect on society was dramatic.",trap:[],patternNote:"effect on + noun"},
{pattern:"example of",word:"example",prep:"of",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"örneği",example:"This is an example of innovation.",trap:[],patternNote:"example of + noun"},
{pattern:"increase in",word:"increase",prep:"in",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"artış",example:"There is an increase in prices.",trap:["increase of"],patternNote:"increase in + noun"},
{pattern:"influence on",word:"influence",prep:"on",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"üzerindeki etki",example:"Media has influence on youth.",trap:[],patternNote:"influence on + noun"},
{pattern:"interest in",word:"interest",prep:"in",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"ilgi",example:"She has interest in psychology.",trap:[],patternNote:"interest in + noun"},
{pattern:"lack of",word:"lack",prep:"of",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"eksiklik",example:"Lack of funding delayed the project.",trap:[],patternNote:"lack of + noun"},
{pattern:"need for",word:"need",prep:"for",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"ihtiyaç",example:"There is a need for reform.",trap:[],patternNote:"need for + noun"},
{pattern:"reason for",word:"reason",prep:"for",type:"Noun + Prep",risk:"very-high",academic:true,turkish:"sebep",example:"The reason for the delay is unclear.",trap:[],patternNote:"reason for + noun"},

/* ================= HIGH ================= */

{pattern:"ability to",word:"ability",prep:"to",type:"Noun + Prep",risk:"high",academic:true,turkish:"yetenek",example:"She has the ability to solve problems.",trap:[],patternNote:"ability to + verb"},
{pattern:"approach to",word:"approach",prep:"to",type:"Noun + Prep",risk:"high",academic:true,turkish:"yaklaşım",example:"This approach to teaching is effective.",trap:[],patternNote:"approach to + noun"},
{pattern:"attitude toward",word:"attitude",prep:"toward",type:"Noun + Prep",risk:"high",academic:true,turkish:"tutum",example:"His attitude toward change is positive.",trap:[],patternNote:"attitude toward + noun"},
{pattern:"awareness of",word:"awareness",prep:"of",type:"Noun + Prep",risk:"high",academic:true,turkish:"farkındalık",example:"There is awareness of climate issues.",trap:[],patternNote:"awareness of + noun"},
{pattern:"belief about",word:"belief",prep:"about",type:"Noun + Prep",risk:"high",academic:true,turkish:"hakkında inanç",example:"Beliefs about health vary.",trap:[],patternNote:"belief about + noun"},
{pattern:"comparison with",word:"comparison",prep:"with",type:"Noun + Prep",risk:"high",academic:true,turkish:"karşılaştırma",example:"In comparison with last year, sales increased.",trap:[],patternNote:"comparison with + noun"},
{pattern:"confidence in",word:"confidence",prep:"in",type:"Noun + Prep",risk:"high",academic:true,turkish:"güven",example:"She has confidence in her team.",trap:[],patternNote:"confidence in + noun"},
{pattern:"control over",word:"control",prep:"over",type:"Noun + Prep",risk:"high",academic:true,turkish:"üzerinde kontrol",example:"They have control over the market.",trap:[],patternNote:"control over + noun"},
{pattern:"damage to",word:"damage",prep:"to",type:"Noun + Prep",risk:"high",academic:true,turkish:"zarar",example:"The damage to the building was severe.",trap:[],patternNote:"damage to + noun"},
{pattern:"decision about",word:"decision",prep:"about",type:"Noun + Prep",risk:"high",academic:true,turkish:"hakkında karar",example:"They made a decision about funding.",trap:[],patternNote:"decision about + noun"},
{pattern:"difficulty in",word:"difficulty",prep:"in",type:"Noun + Prep",risk:"high",academic:true,turkish:"zorluk",example:"She had difficulty in understanding.",trap:[],patternNote:"difficulty in + gerund"},
{pattern:"effect of",word:"effect",prep:"of",type:"Noun + Prep",risk:"high",academic:true,turkish:"etkisi",example:"The effect of pollution is harmful.",trap:[],patternNote:"effect of + noun"},
{pattern:"evidence of",word:"evidence",prep:"of",type:"Noun + Prep",risk:"high",academic:true,turkish:"kanıt",example:"There is evidence of fraud.",trap:[],patternNote:"evidence of + noun"},
{pattern:"fear of",word:"fear",prep:"of",type:"Noun + Prep",risk:"high",academic:false,turkish:"korku",example:"Fear of failure prevents success.",trap:[],patternNote:"fear of + noun"},
{pattern:"focus on",word:"focus",prep:"on",type:"Noun + Prep",risk:"high",academic:true,turkish:"odak",example:"The focus on quality improved results.",trap:[],patternNote:"focus on + noun"},
{pattern:"impact on",word:"impact",prep:"on",type:"Noun + Prep",risk:"high",academic:true,turkish:"etki",example:"The impact on society was significant.",trap:[],patternNote:"impact on + noun"},
{pattern:"improvement in",word:"improvement",prep:"in",type:"Noun + Prep",risk:"high",academic:true,turkish:"iyileşme",example:"There was improvement in performance.",trap:[],patternNote:"improvement in + noun"},
{pattern:"knowledge of",word:"knowledge",prep:"of",type:"Noun + Prep",risk:"high",academic:true,turkish:"bilgi",example:"She has knowledge of economics.",trap:[],patternNote:"knowledge of + noun"},
{pattern:"opinion about",word:"opinion",prep:"about",type:"Noun + Prep",risk:"high",academic:true,turkish:"hakkında görüş",example:"He expressed his opinion about policy.",trap:[],patternNote:"opinion about + noun"},
{pattern:"solution to",word:"solution",prep:"to",type:"Noun + Prep",risk:"high",academic:true,turkish:"çözüm",example:"We found a solution to the problem.",trap:[],patternNote:"solution to + noun"},

/* ================= MEDIUM (60) ================= */

{pattern:"agreement with",word:"agreement",prep:"with",type:"Noun + Prep",risk:"medium",academic:true,turkish:"anlaşma",example:"They reached agreement with partners.",trap:[],patternNote:"agreement with + person"},
{pattern:"argument about",word:"argument",prep:"about",type:"Noun + Prep",risk:"medium",academic:false,turkish:"tartışma",example:"They had an argument about money.",trap:[],patternNote:"argument about + noun"},
{pattern:"argument for",word:"argument",prep:"for",type:"Noun + Prep",risk:"medium",academic:true,turkish:"lehine argüman",example:"There is an argument for change.",trap:[],patternNote:"argument for + noun"},
{pattern:"authority over",word:"authority",prep:"over",type:"Noun + Prep",risk:"medium",academic:true,turkish:"yetki",example:"He has authority over staff.",trap:[],patternNote:"authority over + noun"},
{pattern:"benefit of",word:"benefit",prep:"of",type:"Noun + Prep",risk:"medium",academic:true,turkish:"yararı",example:"The benefit of exercise is clear.",trap:[],patternNote:"benefit of + noun"},
{pattern:"charge of",word:"charge",prep:"of",type:"Noun + Prep",risk:"medium",academic:false,turkish:"suçlama",example:"He was accused on a charge of theft.",trap:[],patternNote:"charge of + noun"},
{pattern:"complaint about",word:"complaint",prep:"about",type:"Noun + Prep",risk:"medium",academic:false,turkish:"şikayet",example:"She made a complaint about noise.",trap:[],patternNote:"complaint about + noun"},
{pattern:"consequence of",word:"consequence",prep:"of",type:"Noun + Prep",risk:"medium",academic:true,turkish:"sonuç",example:"It was a consequence of policy.",trap:[],patternNote:"consequence of + noun"},
{pattern:"debate about",word:"debate",prep:"about",type:"Noun + Prep",risk:"medium",academic:true,turkish:"tartışma",example:"There is debate about education reform.",trap:[],patternNote:"debate about + noun"},
{pattern:"delay in",word:"delay",prep:"in",type:"Noun + Prep",risk:"medium",academic:true,turkish:"gecikme",example:"There was delay in delivery.",trap:[],patternNote:"delay in + noun"},
{pattern:"discussion about",word:"discussion",prep:"about",type:"Noun + Prep",risk:"medium",academic:true,turkish:"tartışma",example:"They had discussion about policy.",trap:[],patternNote:"discussion about + noun"},
{pattern:"experience in",word:"experience",prep:"in",type:"Noun + Prep",risk:"medium",academic:true,turkish:"deneyim",example:"She has experience in marketing.",trap:[],patternNote:"experience in + field"},
{pattern:"failure of",word:"failure",prep:"of",type:"Noun + Prep",risk:"medium",academic:true,turkish:"başarısızlık",example:"The failure of the system was costly.",trap:[],patternNote:"failure of + noun"},
{pattern:"growth in",word:"growth",prep:"in",type:"Noun + Prep",risk:"medium",academic:true,turkish:"artış",example:"Growth in population is rapid.",trap:[],patternNote:"growth in + noun"},
{pattern:"habit of",word:"habit",prep:"of",type:"Noun + Prep",risk:"medium",academic:false,turkish:"alışkanlık",example:"He has habit of biting nails.",trap:[],patternNote:"habit of + gerund"},
{pattern:"involvement in",word:"involvement",prep:"in",type:"Noun + Prep",risk:"medium",academic:true,turkish:"katılım",example:"His involvement in politics increased.",trap:[],patternNote:"involvement in + noun"},
{pattern:"lack of",word:"lack",prep:"of",type:"Noun + Prep",risk:"medium",academic:true,turkish:"eksiklik",example:"Lack of sleep affects health.",trap:[],patternNote:"lack of + noun"},
{pattern:"movement toward",word:"movement",prep:"toward",type:"Noun + Prep",risk:"medium",academic:true,turkish:"yönelim",example:"There is movement toward reform.",trap:[],patternNote:"movement toward + noun"},
{pattern:"pressure on",word:"pressure",prep:"on",type:"Noun + Prep",risk:"medium",academic:true,turkish:"baskı",example:"There is pressure on governments.",trap:[],patternNote:"pressure on + noun"},
{pattern:"respect for",word:"respect",prep:"for",type:"Noun + Prep",risk:"medium",academic:false,turkish:"saygı",example:"She has respect for teachers.",trap:[],patternNote:"respect for + noun"},
{pattern:"response to",word:"response",prep:"to",type:"Noun + Prep",risk:"medium",academic:true,turkish:"tepki",example:"There was response to criticism.",trap:[],patternNote:"response to + noun"},
{pattern:"role in",word:"role",prep:"in",type:"Noun + Prep",risk:"medium",academic:true,turkish:"rol",example:"He played a role in success.",trap:[],patternNote:"role in + noun"},
{pattern:"support for",word:"support",prep:"for",type:"Noun + Prep",risk:"medium",academic:true,turkish:"destek",example:"There is support for reform.",trap:[],patternNote:"support for + noun"},
{pattern:"threat to",word:"threat",prep:"to",type:"Noun + Prep",risk:"medium",academic:true,turkish:"tehdit",example:"Pollution is a threat to health.",trap:[],patternNote:"threat to + noun"},
{pattern:"view on",word:"view",prep:"on",type:"Noun + Prep",risk:"medium",academic:true,turkish:"görüş",example:"He expressed his view on education.",trap:[],patternNote:"view on + noun"}

  ],

  phrases: [
    { pattern:"in spite of", type:"phrase", risk:"very-high" },
    { pattern:"due to", type:"phrase", risk:"very-high" },
    { pattern:"because of", type:"phrase", risk:"very-high" },
    { pattern:"in contrast to", type:"phrase", risk:"very-high" },
    { pattern:"rather than", type:"phrase", risk:"very-high" },
    { pattern:"in addition to", type:"phrase", risk:"very-high" },
    { pattern:"with regard to", type:"phrase", risk:"very-high" },
    { pattern:"in terms of", type:"phrase", risk:"very-high" },
    { pattern:"prior to", type:"phrase", risk:"very-high" },
    { pattern:"on behalf of", type:"phrase", risk:"very-high" },
    { pattern:"in view of", type:"phrase", risk:"very-high" },
    { pattern:"in case of", type:"phrase", risk:"very-high" },
    { pattern:"regardless of", type:"phrase", risk:"very-high" },
    { pattern:"as a result of", type:"phrase", risk:"very-high" },
    { pattern:"instead of", type:"phrase", risk:"very-high" },
    { pattern:"according to", type:"phrase", risk:"very-high" },
    { pattern:"in favor of", type:"phrase", risk:"high" },
    { pattern:"with respect to", type:"phrase", risk:"high" },
    { pattern:"on account of", type:"phrase", risk:"high" },
    { pattern:"in response to", type:"phrase", risk:"high" }
  ]
};